CREATE ROLE core WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    PASSWORD 'test';

GRANT ALL ON DATABASE test TO core;

CREATE SCHEMA IF NOT EXISTS spatium AUTHORIZATION core;

GRANT ALL ON SCHEMA spatium TO core;