version: '3.7'

networks:
  au-network:
    driver: bridge

services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    container_name: postgresql
    networks:
      - au-network
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: ["start-dev", "--import-realm"]
    restart: on-failure
    container_name: keycloak-local
    networks:
      - au-network
    volumes:
      - ./keycloak/import/realm-import.json:/opt/keycloak/data/import/realm-import.json
    environment:
      #KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-import.json
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8180:8080
    depends_on:
      - postgres