spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coredb}
    username: ${DB_LOGIN:core}
    password: ${DB_PASSWORD:vgzzqszd}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    #show-sql: true

  liquibase:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${URI_SECURITY:http://localhost:8180/realms/ma_account}
          jwk-set-uri: ${URI_JWK:http://localhost:8180/realms/ma_account/protocol/openid-connect/certs}

  application:
    name: "arving"

server:
  port: 8091
