spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/coredb"
    username: "core"
    password: "vgzzqszd"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      #hibernate:
        #dialect: "org.hibernate.dialect.PostgreSQLDialect"
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ma_account
          jwk-set-uri: http://localhost:8180/realms/ma_account/protocol/openid-connect/certs

  application:
    name: "arving"

server:
  port: 8091
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/arving.p12
#    key-alias: arving
#    key-store-password: lomtik



#logging:
#  level:
#    root: info
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
